# Generated by Django 6.1.1 on 2026-09-09 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business / Store Name', max_length=255)),
                ('website_url', models.URLField(blank=True, help_text='Main Website URL', max_length=500, null=True)),
                ('owner_whatsapp', models.CharField(help_text='Owner WhatsApp number (e.g. 919876543210)', max_length=20)),
                ('brand_color', models.CharField(default='#0d9488', help_text='Theme Hex color', max_length=10)),
                ('bot_name', models.CharField(default='AI Sales Assistant', help_text='Name displayed in widget', max_length=100)),
                ('welcome_message', models.TextField(default='Hello! How can I help you today? Ask me about our services, pricing, or catalog.')),
                ('system_prompt', models.TextField(blank=True, help_text='Custom instructions for AI behavior', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique browser session ID', max_length=100)),
                ('visitor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('visitor_phone', models.CharField(blank=True, help_text='Captured WhatsApp / Phone', max_length=30, null=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('transcript', models.JSONField(default=list, help_text='List of chat message history')),
                ('lead_summary', models.TextField(blank=True, help_text='Auto-generated summary', null=True)),
                ('status', models.CharField(choices=[('New', 'New / Uncontacted'), ('Contacted', 'Contacted'), ('Converted', 'Converted / Client Won'), ('Spam', 'Spam / Invalid')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agent_engine.businessclient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('allowed_domains', models.CharField(default='*', help_text='Allowed domains', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agent_engine.businessclient')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('page_title', models.CharField(default='Untitled Page', max_length=255)),
                ('content_text', models.TextField(help_text='Clean extracted textual knowledge for RAG context')),
                ('content_type', models.CharField(choices=[('website_page', 'Website Page'), ('product_catalog', 'Product / Service Item'), ('custom_faq', 'Custom FAQ')], default='website_page', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='agent_engine.businessclient')),
            ],
        ),
    ]
