# Generated by Django 6.1.1 on 2026-09-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Business owner login user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
