# Generated by Django 6.1.1 on 2026-09-11 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0002_businessclient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product or Service Name', max_length=255)),
                ('category', models.CharField(default='General', help_text='Category name e.g. Web Development, Sarees', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in INR', max_digits=12)),
                ('pricing_type', models.CharField(default='one-time', help_text='e.g. one-time, monthly, hourly', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, help_text='Key features or deliverables', null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='agent_engine.businessclient')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
